// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace ProfilePictureContainerModuleScssNamespace {
    export interface IProfilePictureContainerModuleScss {
        fallbackContainer: string;
    }
}

declare const ProfilePictureContainerModuleScssModule: ProfilePictureContainerModuleScssNamespace.IProfilePictureContainerModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: ProfilePictureContainerModuleScssNamespace.IProfilePictureContainerModuleScss;
};

export = ProfilePictureContainerModuleScssModule;
