// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CertificateModuleScssNamespace {
    export interface ICertificateModuleScss {
        stylesBackgroundFallback: string;
    }
}

declare const CertificateModuleScssModule: CertificateModuleScssNamespace.ICertificateModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CertificateModuleScssNamespace.ICertificateModuleScss;
};

export = CertificateModuleScssModule;
