// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace CertificateBackgroundModuleLessNamespace {
    export interface ICertificateBackgroundModuleLess {
        stylesBackground: string;
    }
}

declare const CertificateBackgroundModuleLessModule: CertificateBackgroundModuleLessNamespace.ICertificateBackgroundModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: CertificateBackgroundModuleLessNamespace.ICertificateBackgroundModuleLess;
};

export = CertificateBackgroundModuleLessModule;
