// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PresentationModuleScssNamespace {
    export interface IPresentationModuleScss {
        stylesBackgroundFallback: string;
    }
}

declare const PresentationModuleScssModule: PresentationModuleScssNamespace.IPresentationModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PresentationModuleScssNamespace.IPresentationModuleScss;
};

export = PresentationModuleScssModule;
