// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PresentationBackgroundLowResModuleLessNamespace {
    export interface IPresentationBackgroundLowResModuleLess {
        stylesBackground: string;
    }
}

declare const PresentationBackgroundLowResModuleLessModule: PresentationBackgroundLowResModuleLessNamespace.IPresentationBackgroundLowResModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PresentationBackgroundLowResModuleLessNamespace.IPresentationBackgroundLowResModuleLess;
};

export = PresentationBackgroundLowResModuleLessModule;
