// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace PresentationBackgroundModuleLessNamespace {
    export interface IPresentationBackgroundModuleLess {
        stylesBackground: string;
    }
}

declare const PresentationBackgroundModuleLessModule: PresentationBackgroundModuleLessNamespace.IPresentationBackgroundModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: PresentationBackgroundModuleLessNamespace.IPresentationBackgroundModuleLess;
};

export = PresentationBackgroundModuleLessModule;
