// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SkillsBackgroundModuleLessNamespace {
    export interface ISkillsBackgroundModuleLess {
        stylesBackground: string;
    }
}

declare const SkillsBackgroundModuleLessModule: SkillsBackgroundModuleLessNamespace.ISkillsBackgroundModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SkillsBackgroundModuleLessNamespace.ISkillsBackgroundModuleLess;
};

export = SkillsBackgroundModuleLessModule;
