// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace SkillsModuleScssNamespace {
    export interface ISkillsModuleScss {
        stylesBackgroundFallback: string;
    }
}

declare const SkillsModuleScssModule: SkillsModuleScssNamespace.ISkillsModuleScss & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: SkillsModuleScssNamespace.ISkillsModuleScss;
};

export = SkillsModuleScssModule;
