// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace GreetingsModuleLessNamespace {
    export interface IGreetingsModuleLess {
        stylesContainer: string;
    }
}

declare const GreetingsModuleLessModule: GreetingsModuleLessNamespace.IGreetingsModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: GreetingsModuleLessNamespace.IGreetingsModuleLess;
};

export = GreetingsModuleLessModule;
