// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FirstModalBackgroundModuleLessNamespace {
    export interface IFirstModalBackgroundModuleLess {
        stylesContainer: string;
    }
}

declare const FirstModalBackgroundModuleLessModule: FirstModalBackgroundModuleLessNamespace.IFirstModalBackgroundModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FirstModalBackgroundModuleLessNamespace.IFirstModalBackgroundModuleLess;
};

export = FirstModalBackgroundModuleLessModule;
