// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FirstModalBackgroundLowResModuleLessNamespace {
    export interface IFirstModalBackgroundLowResModuleLess {
        stylesContainer: string;
    }
}

declare const FirstModalBackgroundLowResModuleLessModule: FirstModalBackgroundLowResModuleLessNamespace.IFirstModalBackgroundLowResModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FirstModalBackgroundLowResModuleLessNamespace.IFirstModalBackgroundLowResModuleLess;
};

export = FirstModalBackgroundLowResModuleLessModule;
