// autogenerated by typings-for-css-modules-loader.
// Please do not change this file!
declare namespace FirstModalModuleLessNamespace {
    export interface IFirstModalModuleLess {
        stylesContainer: string;
    }
}

declare const FirstModalModuleLessModule: FirstModalModuleLessNamespace.IFirstModalModuleLess & {
    /** WARNING: Only available when `css-loader` is used without `style-loader` or `mini-css-extract-plugin` */
    locals: FirstModalModuleLessNamespace.IFirstModalModuleLess;
};

export = FirstModalModuleLessModule;
